"""
The dynamic loop: what is left to eat today, given what has been eaten.

Every inbound signal -- a voice call, a WhatsApp text, a meal photo -- lands
here as a log entry. This service recomputes the remaining budget for the day
and produces the next-meal instruction. The plan is not regenerated by an LLM
on every update; it is recalculated arithmetically from measured data, so the
same inputs always give the same answer and a chatty model cannot quietly
move the target.
"""
from datetime import date, datetime
from typing import Any, Dict, List, Optional

from app.services.fitness_service import fitness_service
from app.services.micronutrient_service import micronutrient_service
from app.services.nutrition_service import nutrition_service

# Share of the day's energy each slot is expected to carry.
SLOT_SHARES = {
    "breakfast": 0.25,
    "lunch": 0.35,
    "snack": 0.10,
    "dinner": 0.30,
}

SLOT_ORDER = ["breakfast", "lunch", "snack", "dinner"]

# How far off target before we say something about it.
OVER_TOLERANCE = 1.10
UNDER_TOLERANCE = 0.80


class AdaptationService:
    async def resolve_entries(self, entries: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Turn logged {name, portion_g} into measured foods."""
        resolved, unresolved = [], []
        for entry in entries or []:
            name = (entry.get("name") or "").strip()
            grams = entry.get("portion_g") or 0
            if not name or grams <= 0:
                continue
            food = await nutrition_service.resolve(name)
            if not food:
                unresolved.append(name)
                continue
            scaled = nutrition_service.scale(food, grams)
            scaled["slot"] = entry.get("slot")
            scaled["logged_at"] = entry.get("logged_at")
            resolved.append(scaled)
        return {"resolved": resolved, "unresolved": unresolved}

    async def day_state(self, profile: Dict[str, Any],
                        entries: List[Dict[str, Any]],
                        now_slot: Optional[str] = None) -> Dict[str, Any]:
        """
        Current state of the day: consumed, remaining, and what to do next.

        This is the single source of truth the voice agent and the messaging
        bot both read from, so a phone call and a text message never give
        contradictory advice.
        """
        found = await self.resolve_entries(entries)
        eaten = found["resolved"]

        targets = fitness_service.targets(
            weight_kg=profile.get("weight_kg") or 60,
            height_cm=profile.get("height_cm") or 165,
            age=profile.get("age") or 30,
            gender=profile.get("gender") or "female",
            activity_level=profile.get("activity_level") or "moderate",
            goal_type=profile.get("goal_type") or "maintenance",
            target_calories=profile.get("target_calories"),
        )

        consumed = self._totals(eaten)
        remaining = {
            "calories": round(targets["daily_calorie_target"] - consumed["calories"], 1),
            "protein_g": round(targets["macro_targets"]["protein_g"] - consumed["protein_g"], 1),
            "carbs_g": round(targets["macro_targets"]["carbs_g"] - consumed["carbs_g"], 1),
            "fat_g": round(targets["macro_targets"]["fat_g"] - consumed["fat_g"], 1),
        }

        slots_done = {e.get("slot") for e in eaten if e.get("slot")}
        next_slot = now_slot or self._next_slot(slots_done)

        micro = micronutrient_service.assess(
            eaten,
            age=profile.get("age"),
            gender=profile.get("gender"),
            life_stage=profile.get("life_stage"),
            context={"tea_coffee_timing": profile.get("tea_coffee_timing")},
        ) if eaten else None

        return {
            "date": date.today().isoformat(),
            "targets": targets,
            "consumed": consumed,
            "remaining": remaining,
            "percent_of_calories": (
                round(consumed["calories"] / targets["daily_calorie_target"] * 100, 1)
                if targets["daily_calorie_target"] else 0
            ),
            "slots_logged": sorted(slots_done),
            "next_slot": next_slot,
            "next_meal_guidance": self._next_meal(targets, remaining, next_slot,
                                                  slots_done),
            "micronutrients": micro,
            "unresolved": found["unresolved"],
            "entries_resolved": len(eaten),
            # A ready sentence so the voice agent never has to compose one from
            # raw numbers mid-call. log_meal returns its own; this is the
            # equivalent for "how am I doing so far?".
            "spoken_reply": self._spoken_state(consumed, remaining, targets),
        }

    @staticmethod
    def _spoken_state(consumed, remaining, targets) -> str:
        cal_left = remaining["calories"]
        protein_left = remaining["protein_g"]

        if cal_left < 0:
            return (f"You are {abs(cal_left):.0f} calories over today's target, "
                    f"with {max(protein_left, 0):.0f} grams of protein still to go.")
        return (f"You have {cal_left:.0f} calories and {max(protein_left, 0):.0f} "
                f"grams of protein left for today.")

    # -- guidance ---------------------------------------------------------

    def _next_meal(self, targets, remaining, next_slot, slots_done) -> Dict[str, Any]:
        """
        What the next meal should look like given what is left.

        Deliberately arithmetic: the remaining budget is split over the slots
        that have not happened yet, weighted by their usual share.
        """
        if not next_slot:
            return {
                "slot": None,
                "message": "All meals are logged for today.",
                "calories": 0, "protein_g": 0,
            }

        pending = [s for s in SLOT_ORDER if s not in slots_done]
        weight_total = sum(SLOT_SHARES.get(s, 0.25) for s in pending) or 1.0
        share = SLOT_SHARES.get(next_slot, 0.25) / weight_total

        cal = max(round(remaining["calories"] * share), 0)
        protein = max(round(remaining["protein_g"] * share, 1), 0)

        over = remaining["calories"] < 0
        note = None
        if over:
            note = (
                f"You are {abs(remaining['calories']):.0f} kcal over the day's "
                f"target already. Keep {next_slot} light -- vegetables and "
                f"protein, skip the rice or roti."
            )
        elif protein >= 20:
            note = (
                f"Aim for about {protein:.0f} g protein at {next_slot}. Under "
                f"20 g per meal does not do much for muscle retention."
            )

        return {
            "slot": next_slot,
            "calories": cal,
            "protein_g": protein,
            "pending_slots": pending,
            "over_budget": over,
            "message": note or (
                f"About {cal} kcal and {protein:.0f} g protein for {next_slot}."
            ),
        }

    @staticmethod
    def _next_slot(slots_done) -> Optional[str]:
        for slot in SLOT_ORDER:
            if slot not in slots_done:
                return slot
        return None

    @staticmethod
    def _totals(items) -> Dict[str, float]:
        totals = {}
        for field in ("calories", "protein_g", "carbs_g", "fat_g", "fiber_g"):
            values = [i[field] for i in items if i.get(field) is not None]
            totals[field] = round(sum(values), 2) if values else 0.0
        return totals

    # -- what the agent says on a call ------------------------------------

    def call_script(self, state: Dict[str, Any], slot: str,
                    language: str = "en") -> Dict[str, Any]:
        """
        Context handed to the voice agent when it dials.

        Short on purpose. A phone call is not a dashboard -- one number, one
        instruction, one question. The agent asks what was eaten; the answer
        comes back through log_meal and changes the next call.
        """
        guidance = state.get("next_meal_guidance") or {}
        remaining = state.get("remaining") or {}

        if slot == "breakfast" and not state.get("slots_logged"):
            opening = "Good morning. What are you planning for breakfast today?"
        elif guidance.get("over_budget"):
            opening = (f"You are a bit over today's calories. What did you have "
                       f"for {slot}?")
        else:
            opening = f"What did you have for {slot}?"

        return {
            "slot": slot,
            "language": language,
            "opening_line": opening,
            "facts_for_agent": {
                "calories_remaining": remaining.get("calories"),
                "protein_remaining_g": remaining.get("protein_g"),
                "target_for_this_meal_kcal": guidance.get("calories"),
                "target_for_this_meal_protein_g": guidance.get("protein_g"),
                "guidance": guidance.get("message"),
                "slots_already_logged": state.get("slots_logged"),
            },
            "agent_must": [
                "Ask what was eaten and roughly how much.",
                "Call log_meal with each item and its portion in grams.",
                "State the one number that matters, not the whole plan.",
                "Never give medical advice; if asked, say a dietitian will follow up.",
            ],
        }


adaptation_service = AdaptationService()
